use_frameworks!

platform :ios, '10.0'

target 'MXSExtension_Example' do
  pod 'MXSExtension', :path => '../'

  target 'MXSExtension_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
